import Dice from "./Dice";
import './App.css'

function App() {
  
  return (
    <>
      <h1>Gājienu palīgs</h1>
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
      <Dice />
    </>
  ); 
}

export default App
